export {default as hero1} from "./Ellipse 21.png";
export {default as hero2} from "./Ellipse 22.png";
export {default as hero3} from "./Ellipse 23.png";
export {default as topSecurity} from "./top-security.png";
export {default as seamless} from "./seamless-coin.png";
export {default as supereffImg} from "./superior-efficiency.png";
export {default as yomlogo} from "./logo.png";
export {default as partColl} from "./Frame 6198.png";
export {default as herotopbg} from "./Layer_7-removebg-preview.png";
export {default as herobgright} from "./herobgright.png";
export {default as herobgleft} from "./herobgleft.png";
export {default as sbgleft} from "./sbgleft.png";
export {default as sbgright} from "./sbgright.png";
export {default as commside} from "./commside.png";
export {default as underConstruction} from "./undraw_under_construction_-46-pa.svg";